name: greenglide
description: "Sustainability focused flutter game"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0
  flame: ^1.15.0
  flame_audio: ^2.1.8
  flame_tiled: ^1.18.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  ably_flutter: ^1.2.27
  google_wallet: ^0.1.1
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/models/
    - assets/images/scenery/
    - assets/images/icons/
    - assets/audio/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/lexend.ttf
    - family: Luckiest Guy
      fonts:
        - asset: assets/fonts/luckiestguy.ttf
  