// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkndwOgoj5q9lLqPe9N_AVOHI9BNVhTa4',
    appId: '1:396436559416:web:df6d7957349c2712ef78cd',
    messagingSenderId: '396436559416',
    projectId: 'greenglidee',
    authDomain: 'greenglidee.firebaseapp.com',
    storageBucket: 'greenglidee.appspot.com',
    measurementId: 'G-SRPBBC9D2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlyIuMwsbxnKXmvXdhKnuu0G3y5N-vZ6E',
    appId: '1:396436559416:android:b69c15a62ad3b285ef78cd',
    messagingSenderId: '396436559416',
    projectId: 'greenglidee',
    storageBucket: 'greenglidee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfIvWOUUhP9P3V33x_ibp_YRLQq_m-BB4',
    appId: '1:396436559416:ios:74c1e136495259fdef78cd',
    messagingSenderId: '396436559416',
    projectId: 'greenglidee',
    storageBucket: 'greenglidee.appspot.com',
    iosBundleId: 'co.zanie.greenglide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfIvWOUUhP9P3V33x_ibp_YRLQq_m-BB4',
    appId: '1:396436559416:ios:ac17ac995f5a3699ef78cd',
    messagingSenderId: '396436559416',
    projectId: 'greenglidee',
    storageBucket: 'greenglidee.appspot.com',
    iosBundleId: 'co.zanie.greenglide.RunnerTests',
  );
}
